kittinunf/Result

result/src/main/kotlin/com/github/kittinunf/result/Result.kt, result/src/test/kotlin/com/github/kittinunf/result/ResultTests.kt
also 
renamed get to getAs
renamed dematerialized to get
=> added or function equivalent for elvis operator for nullable types

README.md, result/build.gradle, result/src/main/kotlin/com/github/kittinunf/result/Result.kt, result/src/test/kotlin/com/github/kittinunf/result/ResultTests.kt
Some simplifications you might want to consider. It's a *breaking* change so no hard feelings if you decide to discard this. I tried te rely a bit more on the type information we already have, making it easier for future extensions.
=> Simplification proposition

result/src/main/kotlin/com/github/kittinunf/result/Result.kt, result/src/test/kotlin/com/github/kittinunf/result/ResultTests.kt
Thanks for a nice framework. I just add two functions that might be useful. The idea is from other languages that have option/maybe apis. Also kinda align with Kotlin list apis. Anyway, just ignore it if it doesn't fit here.
Thanks again!
=> Add getOrElse and any

README.md
Sorry I forgot this in the previous commit :)
=> fix Readme (hasFailure)

build.gradle, result/src/main/kotlin/com/github/kittinunf/result/Validation.kt
* Update to Kotlin version 1.0.4
=> Update to version 1.0.4

build.gradle
Update to version 1.1 and Use Kotlin 1.1.2.
=> Bump to version 1.1

.travis.yml, build.gradle, deploy_bintray.sh
=> Add deploy script

README.md, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Release version 1.2

README.md, build.gradle
=> Release version 1.3

build.gradle.kts, deploy_bintray.sh
=> [Release] Update v2.0

gradle.properties
=> Update to latest Kotlin version

gradle.properties
This is to update version 2.1.0
=> [Release] Update version 2.1.0

gradle.properties
=> :arrow_up: [Release] Version 2.2.0

result-coroutines/src/main/kotlin/com/github/kittinunf/result/coroutines/SuspendableResult.kt, result-coroutines/src/test/kotlin/com.github.kittinunf.result.coroutines/SuspendableResultTests.kt, result/src/main/kotlin/com/github/kittinunf/result/Result.kt, result/src/test/kotlin/com/github/kittinunf/result/ResultTests.kt
Here the new methods as we talked in #61
=> Add new getOrElse as well as gerOrNull

gradle.properties
It would be nice to get a new release of the library. I just used that chance to update all deps.
=> :arrow_up: Bump version for release

gradle.properties, result-coroutines/src/main/kotlin/com/github/kittinunf/result/coroutines/SuspendableResult.kt, result-coroutines/src/test/kotlin/com.github.kittinunf.result.coroutines/SuspendableResultTests.kt, result/src/main/kotlin/com/github/kittinunf/result/Result.kt, result/src/test/kotlin/com/github/kittinunf/result/ResultTests.kt
This fixes #18 and requires Kotlin 1.3.x
=> :sparkles: Allow result to have a nullable type

gradle.properties
The release new version to support `Result<V?, E>`. Thanks @Globegitter for all of the hardwork! 👏 x 💯
=> [Version] Release version 3.0.0

README.md, gradle.properties
=> :arrow_up: [New version] Release version 3.1.0

gradle.properties
This is to release the new version for Result v4.0.0.
- Thanks sooo much for all the effort made by @Globegitter #74, this indeed a great improvement on the library.
=> :arrow_up: [4.0.0] Version 4.0.0

result/src/main/kotlin/com/github/kittinunf/result/Result.kt, result/src/test/kotlin/com/github/kittinunf/result/ResultTests.kt
=> Provide functions to unwrap value or error

.github/workflows/Release.yml, gradle.properties, result/build.gradle.kts, result/src/commonTest/kotlin/com/github/kittinunf/result/FactoryTest.kt, result/src/commonTest/kotlin/com/github/kittinunf/result/ResultTest.kt, result/src/commonTest/resources/found.txt, result/src/iosTest/kotlin/com/github/kittinunf/result/ReadFile.kt
This PR update script to support iOS binaries (iosArm64, iosX64)
=> [iOS] Add support to iOS binary

result/src/commonMain/kotlin/com/github/kittinunf/result/Result.kt
https://github.com/kittinunf/Result/issues/90
=> Remove enforced nullability from get()'s return type

result/build.gradle.kts, result/src/commonMain/kotlin/com/github/kittinunf/result/Result.kt, result/src/commonTest/kotlin/com/github/kittinunf/result/ResultTest.kt
This PR adds feature request for `mapBoth` to be able to transform the type for both sides of the Type.
=> :sparkles: [Feature] Add requested feature with transformation for both value and error

gradle.properties
- Release new version for 5.2.0
- Support JS #99 #101
- Add `mapBoth` #96 
- Add `lift(...)` #80 
- Create Result.Success and Failure extension #97 
- Enforce nullability #91
=> :arrow_up: [Release] Version 5.2.0

gradle/libs.versions.toml
Hooray for new Kotlin versions!
https://blog.jetbrains.com/kotlin/2021/08/kotlin-1-5-30-released/
=> Update versions toml for Kotlin versions

result/build.gradle.kts, result/src/commonMain/kotlin/com/github/kittinunf/result/Result.kt, result/src/commonTest/kotlin/com/github/kittinunf/result/ResultTest.kt
=> :sparkles: Implement Contracts!

result/build.gradle.kts
It will be beneficial for anyone who wants to run it on Any Mac computers with  Apple Silicon!
=> Support Apple Silicon Support

.github/workflows/Main.yml, .github/workflows/PR.yml, .github/workflows/Release.yml, gradle/libs.versions.toml
Release Notes: https://blog.jetbrains.com/kotlin/2021/11/kotlin-1-6-0-is-released/
=> :arrow_up: Update Kotlin Version to 1.6.0

README.md, gradle/libs.versions.toml
The objective of this PR is to update Kotlin to 1.6.20
Tasks:
- Update [TOML file](https://github.com/kittinunf/Result/blob/master/gradle/libs.versions.toml)
- Update README
- Run tests successfully
=> Update Kotlin version to 1.6.20

README.md, gradle/libs.versions.toml
=> Upgrade Kotlin 1.7.10

README.md, gradle.properties, gradle/libs.versions.toml, plugins/build.gradle.kts
I thought it would be nice if It is using the current version of Kotlin.
=> Update to Kotlin 1.7.20

gradle.properties
=> [Version] Update to 5.5.0

gradle.properties
=> [Version] Prepare for new version 5.6.0

gradle.properties, result/build.gradle.kts
error on watchX64 arch due to missing arch result libs.
=> watchosX64 arch
